// <auto-generated />
using System;
using EcoSphere.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EcoSphere.Data.Migrations
{
    [DbContext(typeof(EcoSphereDbContext))]
    [Migration("20260630184611_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EcoSphere.Core.Models.EcoCertificate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CertificateImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CertificateName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("IssuingOrganization")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EcoCertificates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CertificateName = "ISO 14001 Çevre Yönetim Sistemi",
                            ExpiryDate = new DateTime(2027, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IssueDate = new DateTime(2025, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IssuingOrganization = "TSE",
                            Status = "Geçerli"
                        },
                        new
                        {
                            Id = 2,
                            CertificateName = "Yeşil Ofis Diploması",
                            ExpiryDate = new DateTime(2026, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IssueDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IssuingOrganization = "WWF Türkiye",
                            Status = "Yenileme Bekliyor"
                        });
                });

            modelBuilder.Entity("EcoSphere.Core.Models.EnergyConsumption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("CO2Equivalent")
                        .HasColumnType("float");

                    b.Property<string>("ConsumptionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateLogged")
                        .HasColumnType("datetime2");

                    b.Property<double>("Quantity")
                        .HasColumnType("float");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("EnergyConsumptions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CO2Equivalent = 480.0,
                            ConsumptionType = "Elektrik",
                            DateLogged = new DateTime(2026, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Quantity = 1200.0,
                            Unit = "kWh",
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            CO2Equivalent = 700.0,
                            ConsumptionType = "Doğalgaz",
                            DateLogged = new DateTime(2026, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Quantity = 350.0,
                            Unit = "m3",
                            UserId = 2
                        });
                });

            modelBuilder.Entity("EcoSphere.Core.Models.SustainabilityAudit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AuditDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("AuditorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Findings")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Recommendations")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SustainabilityAudits");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuditDate = new DateTime(2026, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AuditorName = "Zeynep Kaya",
                            DepartmentName = "Üretim Departmanı",
                            Findings = "Atık ayrıştırma kutuları düzgün kullanılıyor fakat enerji tasarruf bilinci artırılmalı.",
                            Recommendations = "Makine bekleme modları optimize edilmeli.",
                            Score = 85
                        },
                        new
                        {
                            Id = 2,
                            AuditDate = new DateTime(2026, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AuditorName = "Zeynep Kaya",
                            DepartmentName = "Lojistik Departmanı",
                            Findings = "Araç rotaları optimize edilmemiş, emisyon yüksek.",
                            Recommendations = "Yazılım tabanlı rota optimizasyonuna geçilmeli.",
                            Score = 68
                        });
                });

            modelBuilder.Entity("EcoSphere.Core.Models.SustainabilityGoal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("CurrentValue")
                        .HasColumnType("float");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TargetDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TargetMetric")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("TargetValue")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SustainabilityGoals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CurrentValue = 4250.0,
                            Status = "Aktif",
                            TargetDate = new DateTime(2026, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TargetMetric = "CO2 Azaltımı",
                            TargetValue = 10000.0,
                            Title = "Yıllık Karbon Ayak İzi Azaltımı",
                            Unit = "kg CO2"
                        },
                        new
                        {
                            Id = 2,
                            CurrentValue = 72.5,
                            Status = "Aktif",
                            TargetDate = new DateTime(2026, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TargetMetric = "Geri Dönüşüm Oranı",
                            TargetValue = 90.0,
                            Title = "Sıfır Atık Geri Dönüşüm Oranı",
                            Unit = "%"
                        },
                        new
                        {
                            Id = 3,
                            CurrentValue = 500.0,
                            Status = "Tamamlandı",
                            TargetDate = new DateTime(2026, 5, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TargetMetric = "Su Tasarrufu",
                            TargetValue = 500.0,
                            Title = "Su Tasarrufu Kampanyası",
                            Unit = "m3"
                        });
                });

            modelBuilder.Entity("EcoSphere.Core.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Department = "Yönetim",
                            FullName = "Ahmet Yılmaz (Sürdürülebilirlik Yöneticisi)",
                            Password = "admin123",
                            Role = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            Department = "Üretim",
                            FullName = "Mehmet Demir (Tesis Temsilcisi)",
                            Password = "user123",
                            Role = "User",
                            Username = "user"
                        });
                });

            modelBuilder.Entity("EcoSphere.Core.Models.WasteManagement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateLogged")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRecycled")
                        .HasColumnType("bit");

                    b.Property<string>("ReceiptImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("WasteType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("WeightKg")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("WasteManagements");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateLogged = new DateTime(2026, 6, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRecycled = true,
                            UserId = 2,
                            WasteType = "Plastik",
                            WeightKg = 45.0
                        },
                        new
                        {
                            Id = 2,
                            DateLogged = new DateTime(2026, 6, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRecycled = true,
                            UserId = 2,
                            WasteType = "Kağıt",
                            WeightKg = 120.0
                        });
                });

            modelBuilder.Entity("EcoSphere.Core.Models.EnergyConsumption", b =>
                {
                    b.HasOne("EcoSphere.Core.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EcoSphere.Core.Models.WasteManagement", b =>
                {
                    b.HasOne("EcoSphere.Core.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
